OBJS=perfect6502.o netlist_sim.o
OBJS+= apple1basic/apple1basic.o cbmbasic/runtime.o cbmbasic/plugin.o cbmbasic/console.o cbmbasic/emu.o

CFLAGS=-Werror -Wall -O3
CC=cc

all: apple1basic

apple1basic: $(OBJS)
	$(CC) -o apple1basic/apple1basic $(OBJS)

clean:
	rm -f $(OBJS) apple1basic/apple1basic

